draw_set_color(c_gray)
draw_sprite_stretched_ext(spr_gray,1,global.playerx-1500,global.playery-1500,3000,3000,c_white,0.2)
draw_sprite_ext(spr_button_new_1,1,x,y,1,1,0,c_white,alpha1)
//draw_sprite_ext(spr_button_new_2,1,x,y,1,1,0,c_white,alpha2)
draw_set_color(c_white)
draw_set_font(font_5)
draw_text(x,y-25,"Paused")
draw_set_font(font_1)
draw_text(x,y+75,"IT'S NOT REALLY PAUSED")