// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
//global.__objectDepths[0] = -10; // obj_PlayerHead
//global.__objectDepths[1] = -10; // obj_PlayerTorso
global.__objectDepths[2] = 0; // par_hurt
//global.__objectDepths[3] = -10; // obj_gun
global.__objectDepths[4] = 0; // par_collectable
global.__objectDepths[5] = 0; // par_enemy
//global.__objectDepths[6] = 0; // obj_gunfire
global.__objectDepths[7] = 0; // par_player
global.__objectDepths[8] = 0; // par_nowall
//global.__objectDepths[9] = 0; // par_enemywall
//global.__objectDepths[10] = 0; // par_wall
global.__objectDepths[11] = 0; // par_Dcollide
global.__objectDepths[12] = 0; // par_bullet
global.__objectDepths[13] = 0; // par_effectspawn
//global.__objectDepths[14] = -1001; // effect_playerLighting
//global.__objectDepths[15] = -997; // effect_playerLighting_green
global.__objectDepths[16] = 0; // effect_heavyshake
global.__objectDepths[17] = 0; // effect_fizzle
global.__objectDepths[18] = 0; // effect_moving_particle
global.__objectDepths[19] = 0; // obj_particle_spawner
global.__objectDepths[20] = 0; // effect_particle_trail
global.__objectDepths[21] = 0; // obj_dChange
global.__objectDepths[22] = 0; // obj_vMovingEnemy
global.__objectDepths[23] = 0; // obj_lava
global.__objectDepths[24] = 0; // effect_shake
global.__objectDepths[25] = 0; // effect_particle_1
global.__objectDepths[26] = -9; // obj_enemy_float
global.__objectDepths[27] = 0; // obj_control_enemy
global.__objectDepths[28] = -10; // obj_enemy_LOS
global.__objectDepths[29] = -1003; // gui_bullet_count
global.__objectDepths[30] = -2000; // gui_hearts
global.__objectDepths[31] = -1003; // dev_health_count
global.__objectDepths[32] = -10000; // obj_mouse
global.__objectDepths[33] = 0; // obj_coin
global.__objectDepths[34] = 0; // camera_main
global.__objectDepths[35] = 0; // obj_pickup_health
global.__objectDepths[36] = 0; // obj_enemy_turret_dead
global.__objectDepths[37] = -10; // obj_Player
global.__objectDepths[38] = -9; // boss_1
global.__objectDepths[39] = -2000; // obj_powerup_auto
global.__objectDepths[40] = -10; // obj_tutm1
global.__objectDepths[41] = -9; // obj_enemy_turret
global.__objectDepths[42] = -2000; // obj_powerup_homing
global.__objectDepths[43] = -10; // obj_tutm3
global.__objectDepths[44] = -11; // obj_counterarrow
global.__objectDepths[45] = 10; // obj_tutP1
global.__objectDepths[46] = -10; // obj_tutm5
global.__objectDepths[47] = 0; // obj_tutP5
global.__objectDepths[48] = -10; // obj_tutm6
global.__objectDepths[49] = -10; // obj_tutm6_2
global.__objectDepths[50] = 0; // obj_tutP6
global.__objectDepths[51] = -10; // obj_tutP7
global.__objectDepths[52] = 0; // obj_tutm7
global.__objectDepths[53] = -10; // obj_tutP8
global.__objectDepths[54] = -10; // obj_tutm4
global.__objectDepths[55] = 0; // obj_tutm8
global.__objectDepths[56] = -100; // obj_wall
global.__objectDepths[57] = -1000; // obj_wallB
global.__objectDepths[58] = -1000; // obj_door
global.__objectDepths[59] = -1002; // obj_bullet
global.__objectDepths[60] = -1002; // obj_bullet_auto
global.__objectDepths[61] = 10; // obj_tutP2
global.__objectDepths[62] = -1002; // obj_bulletrand1
global.__objectDepths[63] = -1002; // obj_bulletrand3
global.__objectDepths[64] = 0; // obj_stick_ball
global.__objectDepths[65] = 0; // par_walllighting
global.__objectDepths[66] = 0; // alarm_1
global.__objectDepths[67] = 0; // obj_enemybullet
global.__objectDepths[68] = -10; // obj_buttonStart
global.__objectDepths[69] = -10; // obj_buttonTutorial
global.__objectDepths[70] = 0; // obj_buttonBack
global.__objectDepths[71] = -1; // menu_background_green
global.__objectDepths[72] = -1002; // obj_bullet_homing
global.__objectDepths[73] = -1; // menu_background_white
global.__objectDepths[74] = -1001; // menu_scene_Aether
global.__objectDepths[75] = 0; // menu_background_purple
global.__objectDepths[76] = -1000; // menu_scene_cover
global.__objectDepths[77] = 0; // snd_menu_music
global.__objectDepths[78] = 0; // mouse_spawn
global.__objectDepths[79] = 0; // snd_laser_sound
global.__objectDepths[80] = 0; // snd_obj_bounce
global.__objectDepths[81] = 0; // obj_checkpoint
global.__objectDepths[82] = 0; // obj_credits
global.__objectDepths[83] = 0; // obj_spawnpoint
global.__objectDepths[84] = -1002; // obj_bulletrand2
global.__objectDepths[85] = 0; // snd_obj_turret_seen
global.__objectDepths[86] = -10; // obj_tutm2
global.__objectDepths[87] = 0; // obj_tutm9
global.__objectDepths[88] = 0; // obj_tutP3
global.__objectDepths[89] = -8; // obj_tutP9
global.__objectDepths[90] = 0; // obj_tutP4


global.__objectNames[0] = "obj_PlayerHead";
global.__objectNames[1] = "obj_PlayerTorso";
global.__objectNames[2] = "par_hurt";
global.__objectNames[3] = "obj_gun";
global.__objectNames[4] = "par_collectable";
global.__objectNames[5] = "par_enemy";
global.__objectNames[6] = "obj_gunfire";
global.__objectNames[7] = "par_player";
global.__objectNames[8] = "par_nowall";
global.__objectNames[9] = "par_enemywall";
global.__objectNames[10] = "par_wall";
global.__objectNames[11] = "par_Dcollide";
global.__objectNames[12] = "par_bullet";
global.__objectNames[13] = "par_effectspawn";
global.__objectNames[14] = "effect_playerLighting";
global.__objectNames[15] = "effect_playerLighting_green";
global.__objectNames[16] = "effect_heavyshake";
global.__objectNames[17] = "effect_fizzle";
global.__objectNames[18] = "effect_moving_particle";
global.__objectNames[19] = "obj_particle_spawner";
global.__objectNames[20] = "effect_particle_trail";
global.__objectNames[21] = "obj_dChange";
global.__objectNames[22] = "obj_vMovingEnemy";
global.__objectNames[23] = "obj_lava";
global.__objectNames[24] = "effect_shake";
global.__objectNames[25] = "effect_particle_1";
global.__objectNames[26] = "obj_enemy_float";
global.__objectNames[27] = "obj_control_enemy";
global.__objectNames[28] = "obj_enemy_LOS";
global.__objectNames[29] = "gui_bullet_count";
global.__objectNames[30] = "gui_hearts";
global.__objectNames[31] = "dev_health_count";
global.__objectNames[32] = "obj_mouse";
global.__objectNames[33] = "obj_coin";
global.__objectNames[34] = "camera_main";
global.__objectNames[35] = "obj_pickup_health";
global.__objectNames[36] = "obj_enemy_turret_dead";
global.__objectNames[37] = "obj_Player";
global.__objectNames[38] = "boss_1";
global.__objectNames[39] = "obj_powerup_auto";
global.__objectNames[40] = "obj_tutm1";
global.__objectNames[41] = "obj_enemy_turret";
global.__objectNames[42] = "obj_powerup_homing";
global.__objectNames[43] = "obj_tutm3";
global.__objectNames[44] = "obj_counterarrow";
global.__objectNames[45] = "obj_tutP1";
global.__objectNames[46] = "obj_tutm5";
global.__objectNames[47] = "obj_tutP5";
global.__objectNames[48] = "obj_tutm6";
global.__objectNames[49] = "obj_tutm6_2";
global.__objectNames[50] = "obj_tutP6";
global.__objectNames[51] = "obj_tutP7";
global.__objectNames[52] = "obj_tutm7";
global.__objectNames[53] = "obj_tutP8";
global.__objectNames[54] = "obj_tutm4";
global.__objectNames[55] = "obj_tutm8";
global.__objectNames[56] = "obj_wall";
global.__objectNames[57] = "obj_wallB";
global.__objectNames[58] = "obj_door";
global.__objectNames[59] = "obj_bullet";
global.__objectNames[60] = "obj_bullet_auto";
global.__objectNames[61] = "obj_tutP2";
global.__objectNames[62] = "obj_bulletrand1";
global.__objectNames[63] = "obj_bulletrand3";
global.__objectNames[64] = "obj_stick_ball";
global.__objectNames[65] = "par_walllighting";
global.__objectNames[66] = "alarm_1";
global.__objectNames[67] = "obj_enemybullet";
global.__objectNames[68] = "obj_buttonStart";
global.__objectNames[69] = "obj_buttonTutorial";
global.__objectNames[70] = "obj_buttonBack";
global.__objectNames[71] = "menu_background_green";
global.__objectNames[72] = "obj_bullet_homing";
global.__objectNames[73] = "menu_background_white";
global.__objectNames[74] = "menu_scene_Aether";
global.__objectNames[75] = "menu_background_purple";
global.__objectNames[76] = "menu_scene_cover";
global.__objectNames[77] = "snd_menu_music";
global.__objectNames[78] = "mouse_spawn";
global.__objectNames[79] = "snd_laser_sound";
global.__objectNames[80] = "snd_obj_bounce";
global.__objectNames[81] = "obj_checkpoint";
global.__objectNames[82] = "obj_credits";
global.__objectNames[83] = "obj_spawnpoint";
global.__objectNames[84] = "obj_bulletrand2";
global.__objectNames[85] = "snd_obj_turret_seen";
global.__objectNames[86] = "obj_tutm2";
global.__objectNames[87] = "obj_tutm9";
global.__objectNames[88] = "obj_tutP3";
global.__objectNames[89] = "obj_tutP9";
global.__objectNames[90] = "obj_tutP4";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for